version: '3.8'
services:

  # s3
  minio:
    image: minio/minio:RELEASE.2022-05-08T23-50-31Z
    environment:
      MINIO_ROOT_USER: "user"
      MINIO_ROOT_PASSWORD: "password"
    command: server /data --console-address :9001
    volumes:
      - ./tmp/minio:/data:cached
      - ./tmp/certs:/root/.minio/certs
    ports:
      - "9000:9000"
      - "9001:9001"

  # bucket creator
  minio-client:
    image: minio/mc:RELEASE.2022-05-09T04-08-26Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add --insecure myminio https://minio:9000 user password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb --insecure myminio/mybucket;
      exit 0;
      "
  # try to restore database
  litestream-restore:
    image: litestream/litestream:sha-10e25d7c9eb2524254ad533d9bf55a50ec5ac4d7
    entrypoint: /bin/sh
    command: -c "rm -rf /data/* && litestream restore /data/db.sqlite"
    volumes:
      - ./tmp/sqlite:/data
      - ./litestream.yml:/etc/litestream.yml:ro
    depends_on:
      - minio-client

  # my application
  app:
    build:
      context: .
    volumes:
      - ./tmp/sqlite:/data
    ports:
      - "3000:3000"
    healthcheck:
      test: curl -s http://localhost:3000/health
    depends_on:
      - litestream-restore

  # replicate database
  litestream-replicate:
    image: litestream/litestream:sha-10e25d7c9eb2524254ad533d9bf55a50ec5ac4d7
    command: replicate
    volumes:
      - ./tmp/sqlite:/data
      - ./litestream.yml:/etc/litestream.yml:ro
    depends_on:
      app:
        condition: service_healthy